name: Aggiorna statistiche cloc al merge di una PR

on:
  push:
    branches: [ main ]
jobs:
  cloc:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v3

    - name: Installa cloc
      run: |
        sudo apt-get update
        sudo apt-get install cloc

    - name: Calcola linee di codice
      run: |
        cloc src --csv --out=lines_of_code.csv --hide-rate
        cloc src --out=lines_of_code.txt --hide-rate

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update line count"
        file_pattern: "lines_of_code.*"